/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "maquina_de_estados_sintetizado.v:1" *)
module maquina_de_estados_sintetizado(clk, reset, data_in, error, proximo_error, estado_presente, proximo_estado);
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  wire [3:0] _000_;
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  wire _001_;
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  wire [3:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  (* src = "maquina_de_estados_sintetizado.v:2" *)
  input clk;
  (* src = "maquina_de_estados_sintetizado.v:12" *)
  wire [3:0] contador;
  (* src = "maquina_de_estados_sintetizado.v:4" *)
  input [15:0] data_in;
  (* src = "maquina_de_estados_sintetizado.v:5" *)
  output error;
  (* src = "maquina_de_estados_sintetizado.v:7" *)
  output [3:0] estado_presente;
  (* src = "maquina_de_estados_sintetizado.v:6" *)
  output proximo_error;
  (* src = "maquina_de_estados_sintetizado.v:8" *)
  output [3:0] proximo_estado;
  (* src = "maquina_de_estados_sintetizado.v:3" *)
  input reset;
  NOT _085_ (
    .A(estado_presente[3]),
    .Y(_020_)
  );
  NOT _086_ (
    .A(estado_presente[2]),
    .Y(_021_)
  );
  NOT _087_ (
    .A(reset),
    .Y(_022_)
  );
  NOT _088_ (
    .A(contador[2]),
    .Y(_023_)
  );
  NOT _089_ (
    .A(data_in[2]),
    .Y(_024_)
  );
  NOT _090_ (
    .A(data_in[3]),
    .Y(_025_)
  );
  NOT _091_ (
    .A(contador[3]),
    .Y(_026_)
  );
  NAND _092_ (
    .A(contador[1]),
    .B(data_in[1]),
    .Y(_027_)
  );
  NOT _093_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _094_ (
    .A(contador[1]),
    .B(data_in[1]),
    .Y(_029_)
  );
  NOT _095_ (
    .A(_029_),
    .Y(_030_)
  );
  NAND _096_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _097_ (
    .A(_028_),
    .B(_029_),
    .Y(_032_)
  );
  NAND _098_ (
    .A(contador[0]),
    .B(data_in[0]),
    .Y(_033_)
  );
  NOT _099_ (
    .A(_033_),
    .Y(_034_)
  );
  NOR _100_ (
    .A(contador[0]),
    .B(data_in[0]),
    .Y(_035_)
  );
  NOT _101_ (
    .A(_035_),
    .Y(_036_)
  );
  NAND _102_ (
    .A(_033_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _103_ (
    .A(_034_),
    .B(_035_),
    .Y(_038_)
  );
  NOR _104_ (
    .A(_032_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _105_ (
    .A(_031_),
    .B(_037_),
    .Y(_040_)
  );
  NOR _106_ (
    .A(_025_),
    .B(contador[3]),
    .Y(_041_)
  );
  NAND _107_ (
    .A(data_in[3]),
    .B(_026_),
    .Y(_042_)
  );
  NOR _108_ (
    .A(data_in[3]),
    .B(_026_),
    .Y(_043_)
  );
  NAND _109_ (
    .A(_025_),
    .B(contador[3]),
    .Y(_044_)
  );
  NOR _110_ (
    .A(_041_),
    .B(_043_),
    .Y(_045_)
  );
  NAND _111_ (
    .A(_042_),
    .B(_044_),
    .Y(_046_)
  );
  NOR _112_ (
    .A(_023_),
    .B(data_in[2]),
    .Y(_047_)
  );
  NAND _113_ (
    .A(contador[2]),
    .B(_024_),
    .Y(_048_)
  );
  NOR _114_ (
    .A(contador[2]),
    .B(_024_),
    .Y(_049_)
  );
  NAND _115_ (
    .A(_023_),
    .B(data_in[2]),
    .Y(_050_)
  );
  NOR _116_ (
    .A(_047_),
    .B(_049_),
    .Y(_051_)
  );
  NAND _117_ (
    .A(_048_),
    .B(_050_),
    .Y(_052_)
  );
  NOR _118_ (
    .A(_046_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _119_ (
    .A(_045_),
    .B(_051_),
    .Y(_054_)
  );
  NOR _120_ (
    .A(_040_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _121_ (
    .A(_039_),
    .B(_053_),
    .Y(_056_)
  );
  NAND _122_ (
    .A(data_in[11]),
    .B(data_in[12]),
    .Y(_057_)
  );
  NAND _123_ (
    .A(data_in[13]),
    .B(data_in[14]),
    .Y(_058_)
  );
  NOR _124_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NOT _125_ (
    .A(_059_),
    .Y(_060_)
  );
  NOR _126_ (
    .A(_056_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _127_ (
    .A(_055_),
    .B(_059_),
    .Y(_062_)
  );
  NAND _128_ (
    .A(_020_),
    .B(_021_),
    .Y(_063_)
  );
  NAND _129_ (
    .A(estado_presente[0]),
    .B(estado_presente[1]),
    .Y(_064_)
  );
  NOR _130_ (
    .A(estado_presente[0]),
    .B(estado_presente[1]),
    .Y(_065_)
  );
  NOT _131_ (
    .A(_065_),
    .Y(_066_)
  );
  NAND _132_ (
    .A(_064_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _133_ (
    .A(_063_),
    .B(_065_),
    .Y(_068_)
  );
  NOR _134_ (
    .A(_063_),
    .B(_067_),
    .Y(_069_)
  );
  NAND _135_ (
    .A(_064_),
    .B(_068_),
    .Y(_070_)
  );
  NAND _136_ (
    .A(estado_presente[3]),
    .B(estado_presente[2]),
    .Y(_071_)
  );
  NAND _137_ (
    .A(_065_),
    .B(_071_),
    .Y(_072_)
  );
  NOT _138_ (
    .A(_072_),
    .Y(_073_)
  );
  NOR _139_ (
    .A(reset),
    .B(_063_),
    .Y(_074_)
  );
  NOT _140_ (
    .A(_074_),
    .Y(_075_)
  );
  NOR _141_ (
    .A(_072_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _142_ (
    .A(_073_),
    .B(_075_),
    .Y(_077_)
  );
  NOR _143_ (
    .A(_069_),
    .B(_076_),
    .Y(_078_)
  );
  NAND _144_ (
    .A(_070_),
    .B(_077_),
    .Y(_079_)
  );
  NOR _145_ (
    .A(_061_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _146_ (
    .A(error),
    .B(_072_),
    .Y(_081_)
  );
  NOR _147_ (
    .A(_069_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _148_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  NOT _149_ (
    .A(_083_),
    .Y(proximo_error)
  );
  NAND _150_ (
    .A(reset),
    .B(_083_),
    .Y(_084_)
  );
  NOR _151_ (
    .A(contador[0]),
    .B(_084_),
    .Y(_000_[0])
  );
  NAND _152_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_003_)
  );
  NOT _153_ (
    .A(_003_),
    .Y(_004_)
  );
  NOR _154_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_005_)
  );
  NOT _155_ (
    .A(_005_),
    .Y(_006_)
  );
  NAND _156_ (
    .A(_003_),
    .B(_006_),
    .Y(_007_)
  );
  NOR _157_ (
    .A(_084_),
    .B(_007_),
    .Y(_000_[1])
  );
  NAND _158_ (
    .A(contador[2]),
    .B(_004_),
    .Y(_008_)
  );
  NAND _159_ (
    .A(_023_),
    .B(_003_),
    .Y(_009_)
  );
  NAND _160_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  NOR _161_ (
    .A(_084_),
    .B(_010_),
    .Y(_000_[2])
  );
  NAND _162_ (
    .A(contador[3]),
    .B(_008_),
    .Y(_011_)
  );
  NOT _163_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _164_ (
    .A(contador[3]),
    .B(_008_),
    .Y(_013_)
  );
  NOR _165_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _166_ (
    .A(_084_),
    .B(_014_),
    .Y(_000_[3])
  );
  NOR _167_ (
    .A(_022_),
    .B(_083_),
    .Y(_001_)
  );
  NAND _168_ (
    .A(_061_),
    .B(_076_),
    .Y(_015_)
  );
  NOT _169_ (
    .A(_015_),
    .Y(proximo_estado[0])
  );
  NOR _170_ (
    .A(_022_),
    .B(_015_),
    .Y(_002_[0])
  );
  NOR _171_ (
    .A(_062_),
    .B(_070_),
    .Y(proximo_estado[1])
  );
  NAND _172_ (
    .A(reset),
    .B(proximo_estado[1]),
    .Y(_016_)
  );
  NOT _173_ (
    .A(_016_),
    .Y(_002_[1])
  );
  NOR _174_ (
    .A(_056_),
    .B(_059_),
    .Y(_017_)
  );
  NAND _175_ (
    .A(_079_),
    .B(_017_),
    .Y(_018_)
  );
  NOT _176_ (
    .A(_018_),
    .Y(proximo_estado[2])
  );
  NOR _177_ (
    .A(_022_),
    .B(_018_),
    .Y(_002_[2])
  );
  NAND _178_ (
    .A(_056_),
    .B(_079_),
    .Y(_019_)
  );
  NOT _179_ (
    .A(_019_),
    .Y(proximo_estado[3])
  );
  NOR _180_ (
    .A(_022_),
    .B(_019_),
    .Y(_002_[3])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _181_ (
    .C(clk),
    .D(_002_[0]),
    .Q(estado_presente[0])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _182_ (
    .C(clk),
    .D(_002_[1]),
    .Q(estado_presente[1])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _183_ (
    .C(clk),
    .D(_002_[2]),
    .Q(estado_presente[2])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _184_ (
    .C(clk),
    .D(_002_[3]),
    .Q(estado_presente[3])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _185_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador[0])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _186_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador[1])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _187_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador[2])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _188_ (
    .C(clk),
    .D(_000_[3]),
    .Q(contador[3])
  );
  (* src = "maquina_de_estados_sintetizado.v:21" *)
  DFF _189_ (
    .C(clk),
    .D(_001_),
    .Q(error)
  );
endmodule
